id: tapo-c510w
categoria: camera
nome: Tapo C510W
marca: TP-Link
estado: pesquisando
projeto: 2026-camera-de-monitoramento-externa
preco_alvo: null
preco_teto: 800.0
atributos:
  resolucao: 2K_3MP
  visao_noturna: colorida_ate_30m
  ip_rating: IP65
  conexao: wifi
  armazenamento_tipo: sd_ate_512gb_ou_nuvem_tapo_care
  angulo_visao: 85.5_diag_73.5h_41v_graus
  zoom_digital: nenhum
  deteccao_ia: movimento_pessoa_sabotagem
  audio_bidirecional: sim_com_cancelamento_ruido
requisitos_atendidos: {}
descartado_porque: null
